title: Leonardo Wajda
author: Leonardo Wajda
email: dev.leowajda@tuta.io
url: https://leowajda.github.io
baseurl: ""
description: ""

markdown: kramdown
highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

theme_config:
  appearance: "auto"
  date_format: "%Y-%m-%d"
  show_description: false
  lowercase_titles: false

generated_data_namespace: generated
