# frozen_string_literal: true

require_relative 'site_kit/core/constants'
require_relative 'site_kit/core/errors'
require_relative 'site_kit/core/io_helpers'
require_relative 'site_kit/core/validation_helpers'
require_relative 'site_kit/core/path_helpers'
require_relative 'site_kit/core/markdown_helpers'
require_relative 'site_kit/core/collection_helpers'
require_relative 'site_kit/core/record_helpers'
require_relative 'site_kit/core/helpers'

require_relative 'site_kit/catalogs/app_config_repository'
require_relative 'site_kit/catalogs/project_manifest_repository'
require_relative 'site_kit/catalogs/project_registry'
require_relative 'site_kit/catalogs/site_project_presenter'

require_relative 'site_kit/pages/definition'
require_relative 'site_kit/pages/link_resolver'
require_relative 'site_kit/pages/home_context_builder'
require_relative 'site_kit/pages/problem_browser_context_builder'

require_relative 'site_kit/templates/topic_repository'
require_relative 'site_kit/templates/topic_presenter'
require_relative 'site_kit/templates/template_repository'
require_relative 'site_kit/templates/problem_rules'
require_relative 'site_kit/templates/reference_label'
require_relative 'site_kit/templates/code_collections/control_builder'
require_relative 'site_kit/templates/code_collections/action_builder'
require_relative 'site_kit/templates/code_collections/model'
require_relative 'site_kit/templates/code_collections/registry'
require_relative 'site_kit/templates/guide/index_builder'
require_relative 'site_kit/templates/guide/validator'
require_relative 'site_kit/templates/guide/reference_resolver'
require_relative 'site_kit/templates/guide/url_resolver'
require_relative 'site_kit/templates/guide/repository'
require_relative 'site_kit/templates/library_context'
require_relative 'site_kit/templates/library_page_context_builder'

require_relative 'site_kit/flowcharts/edge_router'
require_relative 'site_kit/flowcharts/layout_config'
require_relative 'site_kit/flowcharts/layout_builder'
require_relative 'site_kit/flowcharts/registry'
require_relative 'site_kit/flowcharts/node_payload_builder'
require_relative 'site_kit/flowcharts/page_context_builder'

require_relative 'site_kit/eureka/filter_builder'
require_relative 'site_kit/eureka/browser_record_builder'
require_relative 'site_kit/eureka/topic_index_builder'
require_relative 'site_kit/eureka/problem_topic_builder'
require_relative 'site_kit/eureka/topic_registry'
require_relative 'site_kit/eureka/source_catalog_loader'
require_relative 'site_kit/eureka/implementation'
require_relative 'site_kit/eureka/implementation_loader'
require_relative 'site_kit/eureka/problem'
require_relative 'site_kit/eureka/problem_record_builder'
require_relative 'site_kit/eureka/problem_registry_builder'
require_relative 'site_kit/eureka/catalog_loader'
require_relative 'site_kit/eureka/filter_panel_builder'
require_relative 'site_kit/eureka/problem_table_builder'
require_relative 'site_kit/eureka/page_factory'
require_relative 'site_kit/eureka/project'
require_relative 'site_kit/eureka/context'

require_relative 'site_kit/source_notes/tree_builder'
require_relative 'site_kit/source_notes/catalog_loader'
require_relative 'site_kit/source_notes/document_builder'
require_relative 'site_kit/source_notes/module_builder'
require_relative 'site_kit/source_notes/registry_builder'
require_relative 'site_kit/source_notes/page_payload_builder'
require_relative 'site_kit/source_notes/page_factory'
require_relative 'site_kit/source_notes/project'
require_relative 'site_kit/source_notes/context'

require_relative 'site_kit/search/record'
require_relative 'site_kit/search/record_factory'
require_relative 'site_kit/search/problem_record_builder'
require_relative 'site_kit/search/template_record_builder'
require_relative 'site_kit/search/flowchart_record_builder'
require_relative 'site_kit/search/source_record_builder'
require_relative 'site_kit/search/writing_record_builder'
require_relative 'site_kit/search/page_record_builder'
require_relative 'site_kit/search/index_builder'

require_relative 'site_kit/jekyll_runtime/site_loader'
require_relative 'site_kit/jekyll_runtime/generated_page'
require_relative 'site_kit/jekyll_runtime/generated_page_registry'
require_relative 'site_kit/checks/internal_links'
require_relative 'site_kit/checks/seo_metadata'
require_relative 'site_kit/checks/site_invariants'
require_relative 'site_kit/checks/source_catalogs'

require_relative 'site_kit/build/context'
require_relative 'site_kit/build/validator'
